"""loyalty_referral_recently_viewed

Revision ID: 9c7c227da2ed
Revises: bdd558accedd
Create Date: 2026-06-09 20:35:49.229603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7c227da2ed'
down_revision: Union[str, None] = 'bdd558accedd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recently_viewed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recently_viewed_product', 'recently_viewed', ['product_id'], unique=False)
    op.create_index('idx_recently_viewed_session', 'recently_viewed', ['session_id'], unique=False)
    op.create_index('idx_recently_viewed_user', 'recently_viewed', ['user_id'], unique=False)
    op.create_table('loyalty_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_loyalty_order', 'loyalty_transactions', ['order_id'], unique=False)
    op.create_index('idx_loyalty_user', 'loyalty_transactions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('referral_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('referred_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['referred_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_column('users', 'referred_by')
    op.drop_column('users', 'referral_code')
    op.drop_index('idx_loyalty_user', table_name='loyalty_transactions')
    op.drop_index('idx_loyalty_order', table_name='loyalty_transactions')
    op.drop_table('loyalty_transactions')
    op.drop_index('idx_recently_viewed_user', table_name='recently_viewed')
    op.drop_index('idx_recently_viewed_session', table_name='recently_viewed')
    op.drop_index('idx_recently_viewed_product', table_name='recently_viewed')
    op.drop_table('recently_viewed')
    # ### end Alembic commands ###
