export const NOTIFICATION_TYPES = {
  NEW_ORDER: 'NEW_ORDER',
  LOW_STOCK: 'LOW_STOCK',
  SUPPORT_TICKET: 'SUPPORT_TICKET',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  SYSTEM: 'SYSTEM',
};

export const CATEGORY_FILTERS = {
  orders: [NOTIFICATION_TYPES.NEW_ORDER, NOTIFICATION_TYPES.ORDER_CANCELLED, NOTIFICATION_TYPES.PAYMENT_FAILED],
  inventory: [NOTIFICATION_TYPES.LOW_STOCK],
  support: [NOTIFICATION_TYPES.SUPPORT_TICKET],
  system: [NOTIFICATION_TYPES.SYSTEM],
};
